// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EntityFrameworkCoreScaffoldingVSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EntityFrameworkCoreScaffoldingVSExtensionString = "d8d678c4-3772-4ddb-bec1-552ed6ca0e48";
        public static Guid EntityFrameworkCoreScaffoldingVSExtension = new Guid(EntityFrameworkCoreScaffoldingVSExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ScaffoldingMenuGroup = 0x0001;
        public const int RunScaffoldingCommand = 0x0100;
        public const int OpenConfigCommand = 0x0200;
    }
}